#!/bin/bash

# Stop if there is an error in any command below
set -e

cd /opt/memes

if [ ! -d "deps" ]; then
    mix local.hex --force
    mix deps.get
fi

if [ ! -d "assets/node_modules" ]; then
    npm install --prefix assets
fi

if [ ! -d "priv/static" ]; then
    npm run build --prefix assets
fi

mix local.rebar --force
mix ecto.create
mix ecto.migrate
mix run priv/repo/seeds.exs
iex -S mix
